import jsPDF from "jspdf";

export const downloadSchedulePDF = (schedule: string, prompt: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 20;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("IntelliSchedule AI", margin, y);
  y += 10;

  // Prompt
  doc.setFontSize(10);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(120);
  const promptLines = doc.splitTextToSize(`Prompt: ${prompt}`, maxWidth);
  doc.text(promptLines, margin, y);
  y += promptLines.length * 5 + 8;

  // Separator
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Schedule content
  doc.setTextColor(30);
  const lines = schedule.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      y += 4;
      continue;
    }

    // Check for page break
    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    if (/^day\s*\d/i.test(trimmed)) {
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 130, 100);
      doc.text(trimmed, margin, y);
      y += 7;
    } else if (/^💡/i.test(trimmed)) {
      doc.setFontSize(10);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(100, 80, 160);
      const tipLines = doc.splitTextToSize(trimmed, maxWidth);
      doc.text(tipLines, margin, y);
      y += tipLines.length * 5 + 2;
    } else {
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40);
      const wrapped = doc.splitTextToSize(trimmed, maxWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 5 + 2;
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(160);
  doc.text(
    `Generated by IntelliSchedule AI — ${new Date().toLocaleDateString()}`,
    margin,
    doc.internal.pageSize.getHeight() - 10
  );

  doc.save("schedule.pdf");
};
